###########
# site.title, site.url, site.author.name

title:   "Jekyll Syntax Highlighter Sandbox / Examples"
author:
  name:  "Planet Jekyll Team"

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: /sandbox-syntax-highlighter
url:  "http://planetjekyll.github.io/sandbox-syntax-highlighter"


########
# more settings

highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge


exclude:
- README.md


safe: true
lsi: false
